# Site settings
title: Japan lovers
email: adopi.naj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    on aime le japon :)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "jekyll.rb" # the base hostname & protocol for your site
twitter_username: AdoPi
github_username:  AdoPi

# Build settings
markdown: kramdown
